services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    container_name: bentopdf
    restart: unless-stopped
    networks:
      - proxy

    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.bentopdf.rule=Host(`bentopdf.${DOMAIN}`)"
      - "traefik.http.routers.bentopdf.entrypoints=websecure"
      - "traefik.http.routers.bentopdf.tls=true"
      - "traefik.http.routers.bentopdf.tls.certresolver=letsencrypt"

      # Authelia middleware
      - "traefik.http.routers.bentopdf.middlewares=authelia@docker"

  networks:
    proxy:
      external: true