services:
  bentopdf:
    image: bentopdf/bentopdf-simple:latest
    container_name: bentopdf
    #ports:
      #-
    restart: unless-stopped
    networks:
      - proxy

    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.routers.bentopdf.rule=Host(`bentopdf.${DOMAIN}`)"
      - "traefik.http.routers.bentopdf.entrypoints=websecure"
      - "traefik.http.routers.bentopdf.tls=true"
      - "traefik.http.routers.bentopdf.tls.certresolver=${CERTRESOLVER}"
      - "traefik.http.services.bentopdf.loadbalancer.server.port=8080"
      - "traefik.http.routers.bentopdf.tls.domains[0].main=${DOMAIN}"                                                                                         
      - "traefik.http.routers.bentopdf.tls.domains[0].sans=*.${DOMAIN}"
      

      # Authelia middleware
      - "traefik.http.routers.bentopdf.middlewares=authelia@docker"

networks:
  proxy:
    external: true