services:
    omni-tools:
      image: iib0011/omni-tools:latest
      container_name: omni-tools
      
      restart: unless-stopped
      
      networks:
        - proxy
      
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.omnitools.rule=Host(`omnitools.${DOMAIN}`)"
        - "traefik.http.routers.omnitools.entrypoints=websecure"
        - "traefik.http.routers.omnitools.tls=true"
        - "traefik.http.routers.omnitools.tls.certresolver=${CERTRESOLVER}"
        - "traefik.http.services.omnitools.loadbalancer.server.port=80"
        - "traefik.http.routers.omnitools.tls.domains[0].main=${DOMAIN}"
        - "traefik.http.routers.omnitools.tls.domains[0].sans=*.${DOMAIN}"

        # Authelia middleware
        - "traefik.http.routers.omnitools.middlewares=authelia@docker"

networks:
  proxy:
    external: true